### ISSUE TITLE
Add jam version command

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/jam#13]
## What happened?

* What were you attempting to do?
Find out which version of the jam CLI I had installed on my workstation

* What did you expect to happen?
`jam version` and/or `jam --version` and/or `jam -v` would return the semver version of the installed CLI.

* What was the actual behavior? Please provide log output, if possible.
```bash
jam --version
Error: unknown flag: --version
Usage:
  jam [command]

Available Commands:
  completion          generate the autocompletion script for the specified shell
  help                Help about any command
  pack                package buildpack
  summarize           summarize buildpackage
  update-builder      update builder
  update-buildpack    update buildpack
  update-dependencies updates all depdendencies in a buildpack.toml according to metadata.constraints

Flags:
  -h, --help   help for jam

Use "jam [command] --help" for more information about a command
```

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by ForestEckhardt** [comment]
I think we could do this with build time arguments in Go then we could continue to have a self contained binary.
