### ISSUE TITLE
Create stack without docker daemon

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [paketo-buildpacks/jam#159]
Currently using `jam create-stack` requires access to a docker daemon. That put some burden on the CI since this is not always easy, e.g. running on kubernetes.

## Describe the Enhancement

Remove all direct dependencies to the docker daemon.

## Possible Solution

For example using a different kind of sink for the `go-containerregistry`. Using `BuildKit` should still be fine since it can be used without the docker daemon.

## Motivation

It would be easier to use `jam create-stack`, especially in a CI system that do not have easy access to a docker daemon.

**Comment by robdimsdale** [comment]
Hey @c0d1ngm0nk3y - I'd be open to this as long as it doesn't have any negative impact on performance or maintainability of the stack creation.

If you want to put together a PR exploring this we'd be happy to take a look.

**Comment by c0d1ngm0nk3y** [comment]
Sounds good. We are currently evaluating options n this and we will update this issue.

**Comment by robdimsdale** [comment]
@c0d1ngm0nk3y - I assume that this became a low priority for you?

Any objections to me closing this out? It's not something we're likely to do without community input.

**Comment by c0d1ngm0nk3y** [comment]
> I assume that this became a low priority for you?

You are right. Sorry for not closing it.
