### ISSUE TITLE
Please provide `arm64` versions of the build artifacts in future GitHub releases

### ISSUE THREAD

**Issue by maliksalman** [paketo-buildpacks/jam#240]
Please provide `arm64` versions of the build artifacts in future GitHub releases

## Describe the Enhancement
Currently the automated build/release mechanism only builds/publishes artifacts for `amd64` architecture. With the proliferation of `arm64` processors (Apple M1/M2, Raspberry PI, AWS Graviton, etc) providing `arm64` artifacts in the releases would benefit those using these processors.

## Possible Solution
*golang* builds can easily output binaries for `arm64` architecture in addition to the existing `amd64` architecture. No source code needs to change, just the build automation scripts. I can submit a pull-request to do this.

## Motivation
Want to take advantage of exciting new ARM64 based hardware and pre-built ARM64 `jam` binaries would be essential in creating stack and builder images for that platform.

**Comment by robdimsdale** [comment]
Yes - I think this is completely reasonable and something we should do. You've now got me slightly confused as to how we run pack on our ARM64 macbooks 🤔 

If you're willing to submit a PR that would be great!

**Comment by maliksalman** [comment]
I’ll submit a PR later today. I bet that its Apple’s Rosetta2 that lets you run `amd64` Darwin binaries on your M1 Macs.

**Comment by dashaun** [comment]
@maliksalman Yes, you are correct!  I was just about to commit a very similar PR.  You made my day!

**Comment by robdimsdale** [comment]
This is complete with #241 merged and [`v2.1.1` released](https://github.com/paketo-buildpacks/jam/releases/tag/v2.1.1).

🎉
