### ISSUE TITLE
`jam update-builder` is clobbering extensions

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/jam#294]
This can be seen in the this PR https://github.com/paketo-community/builder-ubi-base/pull/6 instead of updating the extensions the section is clobbered as it is not currently accounted for in the update logic. The `update-builder` command should be updated to account for extension and to attempt to upgrade them.

**Comment by mhdawson** [comment]
Working on PR to support extensions in this branch - https://github.com/mhdawson/jam/pull/new/support-extensions-in-update.  It's getting pretty close.

Have reached the docker pull limit and I don't see the option for a token so I may just have to wait until tomorrow to continue.

**Comment by mhdawson** [comment]
PR to fix - https://github.com/paketo-buildpacks/jam/pull/302
