### ISSUE TITLE
Error: No such file or directory for docker >=25.0.0

### ISSUE THREAD

**Issue by pacostas** [paketo-buildpacks/jam#335]
## Expected Behavior

`jam create-stack` should create a `build.oci` and `run.oci` output files

## Current Behavior

`jam create-stack`  fails with bellow error :
```
Using jam 2.7.0
Building io.buildpacks.stacks.jammy
  Building on linux/amd64
    Building base images
Error: open /tmp/2573542004/wsnpmg4jaz/blobs/sha256/d101c9453715a978a2a520f553588e77dfb4236762175eba61c5c264a449c75d: no such file or directory
Usage:
  jam create-stack [flags]

Flags:
      --build-output string   path to output the build image OCI archive (required)
      --build-ref string      reference that specifies where to publish the build image (required)
      --config string         path to a stack descriptor file (required)
  -h, --help                  help for create-stack
      --label strings         additional image label to be added to build and run image
      --publish               publish to a registry
      --run-output string     path to output the run image OCI archive (required)
      --run-ref string        reference that specifies where to publish the run image (required)
      --secret strings        secret to be passed to your Dockerfile
      --unbuffered            do not buffer image contents into memory for fast access

failed to execute: open /tmp/2573542004/wsnpmg4jaz/blobs/sha256/d101c9453715a978a2a520f553588e77dfb42367
```
## Steps to Reproduce

1. Install Docker version 25 and above
2. git clone https://github.com/paketo-buildpacks/jammy-base-stack.git
3. cd jammy-base-stack
4. ./scripts/create.sh

**Comment by sophiewigmore** [comment]
What version of Docker were you using before 25?

**Comment by pacostas** [comment]
24.0.9

**Comment by sophiewigmore** [comment]
I will try to reproduce this myself and get back to you

**Comment by matthenry87** [comment]
Also experiencing this with:

jam 2.7.0
Docker version 25.0.3, build 4debf41

**Comment by sophiewigmore** [comment]
@matthenry87 @pacostas I merged in some docker library go.mod bumps just now and released https://github.com/paketo-buildpacks/jam/releases/tag/v2.7.1. Can you please try it out with Docker 25 and let me know if the issues are resolved?

**Comment by matthenry87** [comment]
Works now, thanks!

**Comment by pacostas** [comment]
@sophiewigmore yeap, it works! thank you ! :) Feel free to close this issue.
