### ISSUE TITLE
Get a default stack descriptor file for `create-stack`

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/jam#56]
With #52, the `jam create-stack` command was introduced. This command is very useful for simplified stack creation, but requires users to provide a stack descriptor file. This file is defined clearly, but still requires a user to go and look at this outline, and create their own.

## Issue
We should have a way to provide users with a basic stack descriptor file, likely through a `jam create-stack-descriptor` or by providing a default file if none are provided to the `create-stack` command. 

## Outcome
Some mechanism is available in jam to easily get a default stack descriptor file without having to create one from scratch.

**Comment by robdimsdale** [comment]
For anyone following along, there's some discussion about purpose and direction on the associated PR: https://github.com/paketo-buildpacks/jam/pull/165
