### ISSUE TITLE
Failure to build stack when build and run Dockerfiles are the same

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/jam#66]
In https://github.com/paketo-buildpacks/dotnet-core/issues/653, a user (@lamw) reported seeing a failure when building a Powershell-based image on Mac:
```
❯ jam create-stack --config stack.toml --build-output build.oci --run-output run.oci
Building photon-powershell
  Building on linux/amd64
    Building base images
      Build complete for base images
    build: Decorating base image
      Adding CNB_* environment variables
      Adding io.buildpacks.stack.* labels
      Creating cnb user
    run: Decorating base image
      Adding io.buildpacks.stack.* labels
      Creating cnb user
    build: Updating image
    run: Updating image
Error: Error: No such image: paketo.io/stack/87zgdlj0a5
Usage:
  jam create-stack [flags]

Flags:
      --build-output string   path to output the build image OCI archive (required)
      --config string         path to a stack descriptor file (required)
  -h, --help                  help for create-stack
      --run-output string     path to output the run image OCI archive (required)
      --secret strings        secret to be passed to your Dockerfile

failed to execute: Error: No such image: paketo.io/stack/87zgdlj0a5
```
I was able to reproduce this error on my Mac, when passing in the same `stack.toml` file, and setting up a [powershell Dockerfile ](https://github.com/PowerShell/PowerShell-Docker/blob/master/release/7-2/alpine313/docker/Dockerfile). 

It appears that the run image build phase succeeds and the image is on the Docker daemon during the build, but for some reason the run image is missing from the Docker daemon when the run image update step runs.

It looks like this error does not occur when building the [Tiny stack](https://github.com/paketo-buildpacks/stacks/tree/config-file/tiny), for example on Mac

## Issue
We should investigate why this is occurring and put in a fix to the `create-stack` codebase. If it's a problem with the Dockerfile used, we should make usage information clearer for users.
We should also try to reproduce this failure on a linux machine and see if the same error crops up.

**Comment by sophiewigmore** [comment]
Update: this error occurs on both Linux and Mac.

**Comment by sophiewigmore** [comment]
Another update: this error appears to be from using the same Dockerfile for both the build and run images. It appears that the two generated images have the same Image ID in the docker daemon which causes some problems with the run image. I was able to successfully build by using a separate Dockerfile for the run image with a small change made to it.

**Comment by sophiewigmore** [comment]
Should users be able to use the same Dockerfile for build and run? If so, this is a bug we should resolve.

**Comment by robdimsdale** [comment]
@sophiewigmore a quick clarification - is this a problem from using the exact same Dockerfile, or is it also reproducible when using different Dockerfiles with identical content but different file names?

**Comment by sophiewigmore** [comment]
@robdimsdale identical content but different file names still produce the buggy behaviour
